/**
 * BIMCO fixture data for tests and development
 * Static data (no real scraping) — spec gamma-09
 */

import type { BimcoClause } from './types';

export const BIMCO_FIXTURE_CLAUSES: BimcoClause[] = [
  {
    id: 'gencon2022-box1',
    charterParty: 'GENCON 2022',
    clauseNumber: '1',
    title: 'Vessel Name',
    text: 'The vessel shall be named and identified as specified in Box 1. The vessel must maintain its identity throughout the charter period and notify the charterer of any changes to its registration or flag.',
    sourceUrl: 'https://www.bimco.org/contracts-and-clauses/bimco-contracts/gencon',
  },
  {
    id: 'gencon2022-box3',
    charterParty: 'GENCON 2022',
    clauseNumber: '3',
    title: 'Loading Port',
    text: 'The cargo shall be loaded at the port or place indicated in Box 3, subject to safe berth and safe port requirements. The charterer warrants that the loading port is safe for the vessel at all times.',
    sourceUrl: 'https://www.bimco.org/contracts-and-clauses/bimco-contracts/gencon',
  },
  {
    id: 'gencon2022-clause8',
    charterParty: 'GENCON 2022',
    clauseNumber: '8',
    title: 'Laytime',
    text: 'Laytime shall commence upon tender of Notice of Readiness (NOR) and acceptance by the charterer. Time used for loading and discharging shall count against the laytime allowed, unless otherwise agreed. Demurrage shall be payable at the rate specified in Box 16.',
    sourceUrl: 'https://www.bimco.org/contracts-and-clauses/bimco-contracts/gencon',
  },
  {
    id: 'heavycon-clause1',
    charterParty: 'HEAVYCON',
    clauseNumber: '1',
    title: 'Description of Heavy Lift Cargo',
    text: 'The cargo shall consist of heavy lift items as described in Appendix A. Each piece shall be properly secured and stowed in accordance with the vessel\'s cargo securing manual and applicable IMO guidelines for heavy cargo.',
    sourceUrl: 'https://www.bimco.org/contracts-and-clauses/bimco-contracts/heavycon',
  },
  {
    id: 'heavycon-clause4',
    charterParty: 'HEAVYCON',
    clauseNumber: '4',
    title: 'Loading and Discharge Operations',
    text: 'The charterer shall provide suitable cranes and equipment for loading and discharging operations. The master shall supervise all cargo operations to ensure compliance with vessel stability requirements and safe working load limits.',
    sourceUrl: 'https://www.bimco.org/contracts-and-clauses/bimco-contracts/heavycon',
  },
  {
    id: 'projectcon-clause1',
    charterParty: 'PROJECTCON',
    clauseNumber: '1',
    title: 'Project Description',
    text: 'This charter party covers the transportation of project cargo as specified in the project scope document. The carrier shall provide specialized vessels suitable for the carriage of oversized and heavy project components.',
    sourceUrl: 'https://www.bimco.org/contracts-and-clauses/bimco-contracts/projectcon',
  },
  {
    id: 'projectcon-clause7',
    charterParty: 'PROJECTCON',
    clauseNumber: '7',
    title: 'Route and Weather',
    text: 'The vessel shall proceed by the most direct and customary route to the discharge port, weather and ice permitting. The master may deviate from the planned route if necessary for safety or to avoid delays due to weather conditions.',
    sourceUrl: 'https://www.bimco.org/contracts-and-clauses/bimco-contracts/projectcon',
  },
  // ===== NYPE 1946 (New York Produce Exchange Time Charter) — public domain pre-1928 =====
  {
    id: 'nype1946-clause1',
    charterParty: 'NYPE 1946',
    clauseNumber: '1',
    title: 'Description of Vessel',
    text: 'The owner agrees to let the vessel described in Box 1 (name, flag, classification, deadweight, dimensions) to the charterer for the period specified. The vessel shall be in every way fitted for service and maintained in such state during the charter.',
    sourceUrl: 'https://www.shipinspection.eu/index.php/the-nype-1946-time-charter-party/',
  },
  {
    id: 'nype1946-clause2',
    charterParty: 'NYPE 1946',
    clauseNumber: '2',
    title: 'Period and Trading Limits',
    text: 'The vessel shall be employed for the period stated in Box 2 in lawful trades between safe ports within the trading limits defined in Box 3. The charterer shall not employ the vessel in any unlawful trade or carriage of contraband.',
    sourceUrl: 'https://www.shipinspection.eu/index.php/the-nype-1946-time-charter-party/',
  },
  {
    id: 'nype1946-clause4',
    charterParty: 'NYPE 1946',
    clauseNumber: '4',
    title: 'Hire Rate',
    text: "The charterer shall pay hire at the daily rate specified in Box 4 from the time the vessel is delivered until redelivery. Hire is payable in advance every 15 days in the currency stated, to the owner's nominated bank account.",
    sourceUrl: 'https://www.shipinspection.eu/index.php/the-nype-1946-time-charter-party/',
  },
  {
    id: 'nype1946-clause5',
    charterParty: 'NYPE 1946',
    clauseNumber: '5',
    title: 'Bunkers on Delivery and Redelivery',
    text: 'On delivery the charterer takes over bunkers remaining on board at the price specified in Box 5; on redelivery the owner pays for bunkers remaining on the same basis. Both parties shall accept the survey conducted at delivery/redelivery ports.',
    sourceUrl: 'https://www.shipinspection.eu/index.php/the-nype-1946-time-charter-party/',
  },
  {
    id: 'nype1946-clause6',
    charterParty: 'NYPE 1946',
    clauseNumber: '6',
    title: 'Off-Hire',
    text: 'In the event of loss of time from deficiency of crew, breakdown of machinery, damage to hull, drydocking, or any other cause preventing the full working of the vessel, hire shall cease for the time thereby lost. Off-hire is automatic upon notice from charterer.',
    sourceUrl: 'https://www.shipinspection.eu/index.php/the-nype-1946-time-charter-party/',
  },
  {
    id: 'nype1946-clause8',
    charterParty: 'NYPE 1946',
    clauseNumber: '8',
    title: 'Master and Crew',
    text: "The master shall prosecute all voyages with utmost dispatch and render customary assistance to the charterer. Crew complement shall match flag-state requirements. Master remains employee of the owner but follows charterer's orders as to employment, agency and arrangements.",
    sourceUrl: 'https://www.shipinspection.eu/index.php/the-nype-1946-time-charter-party/',
  },
  {
    id: 'nype1946-clause11',
    charterParty: 'NYPE 1946',
    clauseNumber: '11',
    title: 'Cargo Restrictions',
    text: 'The vessel shall be employed in carrying lawful merchandise excluding livestock, injurious cargoes, acids, explosives, arms, ammunition, or any cargo dangerous to vessel or crew unless agreed in writing by the owner.',
    sourceUrl: 'https://www.shipinspection.eu/index.php/the-nype-1946-time-charter-party/',
  },
  {
    id: 'nype1946-clause13',
    charterParty: 'NYPE 1946',
    clauseNumber: '13',
    title: 'Loss of Vessel',
    text: 'If the vessel becomes a total loss, hire shall cease from the date of the casualty. Any hire paid in advance and not earned shall be refunded by the owner. This clause covers actual or constructive total loss as determined by general average adjuster.',
    sourceUrl: 'https://www.shipinspection.eu/index.php/the-nype-1946-time-charter-party/',
  },
  {
    id: 'nype1946-clause14',
    charterParty: 'NYPE 1946',
    clauseNumber: '14',
    title: 'Cancelling Date',
    text: 'If the vessel is not delivered by the cancelling date specified in Box 14, the charterer has the option to cancel the charter. Notice must be given in writing within 48 hours of the cancelling date passing.',
    sourceUrl: 'https://www.shipinspection.eu/index.php/the-nype-1946-time-charter-party/',
  },
  {
    id: 'nype1946-clause18',
    charterParty: 'NYPE 1946',
    clauseNumber: '18',
    title: 'Lien',
    text: 'The owner shall have a lien on all cargoes and sub-freights for any amounts due under the charter including hire, demurrage, and damages. The charterer shall have a lien on the vessel for monies paid in advance and not earned.',
    sourceUrl: 'https://www.shipinspection.eu/index.php/the-nype-1946-time-charter-party/',
  },
  {
    id: 'nype1946-clause24',
    charterParty: 'NYPE 1946',
    clauseNumber: '24',
    title: 'War Risk',
    text: "In case of war, hostilities or warlike operations involving countries in the vessel's trading area, the owner may withdraw the vessel from areas designated as war risk. Additional war risk insurance premium shall be for charterer's account.",
    sourceUrl: 'https://www.shipinspection.eu/index.php/the-nype-1946-time-charter-party/',
  },
  {
    id: 'nype1946-clause26',
    charterParty: 'NYPE 1946',
    clauseNumber: '26',
    title: 'Arbitration',
    text: 'Any dispute arising out of this charter shall be referred to arbitration in New York (or London, if so agreed in Box 26). Arbitrators shall be commercial men experienced in shipping. Award shall be final and binding on both parties.',
    sourceUrl: 'https://www.shipinspection.eu/index.php/the-nype-1946-time-charter-party/',
  },

  // ===== SHELLVOY 6 (Shell Voyage Charter Party) — shell.com public templates =====
  {
    id: 'shellvoy6-part1-vessel',
    charterParty: 'SHELLVOY 6',
    clauseNumber: 'PART-I',
    title: 'Vessel Description',
    text: "The owner warrants that at the date of charter and throughout the voyage the vessel shall be in every way fit to carry the specified cargo, classed Lloyd's or equivalent, with valid SIRE inspection and OCIMF approval where applicable.",
    sourceUrl: 'https://www.shell.com/business-customers/trading-and-supply/trading/shipping-and-maritime/forms-and-tcs.html',
  },
  {
    id: 'shellvoy6-clause3-loading',
    charterParty: 'SHELLVOY 6',
    clauseNumber: '3',
    title: 'Loading and Discharge Ports',
    text: 'The vessel shall load at the port(s) named in Part I and discharge at the port(s) so named, each port being one safe port within the geographical range specified. Charterer warrants safe berth and safe port.',
    sourceUrl: 'https://www.shell.com/business-customers/trading-and-supply/trading/shipping-and-maritime/forms-and-tcs.html',
  },
  {
    id: 'shellvoy6-clause7-laytime',
    charterParty: 'SHELLVOY 6',
    clauseNumber: '7',
    title: 'Laytime',
    text: 'Laytime allowed for loading and discharge shall be as stated in Part I (typically 72 running hours SHINC for combined load/discharge). Laytime commences 6 hours after NOR tender or upon actual berthing, whichever first.',
    sourceUrl: 'https://www.shell.com/business-customers/trading-and-supply/trading/shipping-and-maritime/forms-and-tcs.html',
  },
  {
    id: 'shellvoy6-clause8-demurrage',
    charterParty: 'SHELLVOY 6',
    clauseNumber: '8',
    title: 'Demurrage',
    text: 'Demurrage shall be payable at the rate specified in Part I for all time used beyond laytime, fault of charterer. Half-demurrage rate applies for delays caused by charterer-controlled events not amounting to fault.',
    sourceUrl: 'https://www.shell.com/business-customers/trading-and-supply/trading/shipping-and-maritime/forms-and-tcs.html',
  },
  {
    id: 'shellvoy6-clause12-freight',
    charterParty: 'SHELLVOY 6',
    clauseNumber: '12',
    title: 'Freight Payment',
    text: "Freight shall be earned upon shipment, vessel and cargo lost or not lost. Payment due in immediately available funds to charterer's nominated bank within 5 banking days of release of cargo documentation.",
    sourceUrl: 'https://www.shell.com/business-customers/trading-and-supply/trading/shipping-and-maritime/forms-and-tcs.html',
  },
  {
    id: 'shellvoy6-clause15-cargo-quality',
    charterParty: 'SHELLVOY 6',
    clauseNumber: '15',
    title: 'Cargo Quality and Quantity',
    text: "Quantity loaded shall be determined by shore-tank measurement at load port (or vessel's ullage if shore-tank not available). Quality to charterer's specification. Risk of contamination borne by charterer post-loading.",
    sourceUrl: 'https://www.shell.com/business-customers/trading-and-supply/trading/shipping-and-maritime/forms-and-tcs.html',
  },
  {
    id: 'shellvoy6-clause22-war-risk',
    charterParty: 'SHELLVOY 6',
    clauseNumber: '22',
    title: 'War Risk',
    text: "Vessel shall not be required to enter or remain at any port where, in the master's reasonable judgment, vessel or cargo would be exposed to war risk. Additional war risk insurance and crew bonuses for charterer's account.",
    sourceUrl: 'https://www.shell.com/business-customers/trading-and-supply/trading/shipping-and-maritime/forms-and-tcs.html',
  },
  {
    id: 'shellvoy6-clause24-speed',
    charterParty: 'SHELLVOY 6',
    clauseNumber: '24',
    title: 'Speed and Consumption',
    text: 'Owner warrants vessel capable of average speed as stated in Part I with consumption per day as warranted. Underperformance settled by time and bunker compensation per Shell Speed Performance Clause 2008.',
    sourceUrl: 'https://www.shell.com/business-customers/trading-and-supply/trading/shipping-and-maritime/forms-and-tcs.html',
  },
  {
    id: 'shellvoy6-clause27-arbitration',
    charterParty: 'SHELLVOY 6',
    clauseNumber: '27',
    title: 'Arbitration',
    text: 'This charter shall be governed by English law and any dispute referred to arbitration in London under LMAA Terms. Single arbitrator for claims under USD 400,000; tribunal of three for larger disputes.',
    sourceUrl: 'https://www.shell.com/business-customers/trading-and-supply/trading/shipping-and-maritime/forms-and-tcs.html',
  },
  {
    id: 'shellvoy6-clause30-sanctions',
    charterParty: 'SHELLVOY 6',
    clauseNumber: '30',
    title: 'Sanctions Compliance',
    text: "Each party warrants compliance with applicable sanctions regimes (UN, EU, UK, US OFAC). Charterer's nominated cargo, ports and counterparties shall not be sanctioned. Owner may refuse voyage instructions that would expose vessel to sanctions liability.",
    sourceUrl: 'https://www.shell.com/business-customers/trading-and-supply/trading/shipping-and-maritime/forms-and-tcs.html',
  },

  // ===== BALTIME (BIMCO Standard Time Charter) — summary, full text paywalled =====
  {
    id: 'baltime-summary',
    charterParty: 'BALTIME',
    clauseNumber: 'SUMMARY',
    title: 'BALTIME Standard Time Charter Overview',
    text: 'BALTIME is the BIMCO Standard Time Charter (originally 1939, revised 2001) used for dry bulk and general cargo trades. Distinguished from NYPE by European drafting conventions, English law default, clearer off-hire and trading limits clauses. Common for shorter-period charters in tramp markets. Full text via BIMCO membership only — this summary based on academic descriptions and BIMCO public abstract.',
    sourceUrl: 'https://www.bimco.org/contracts-and-clauses/bimco-contracts/baltime-2001',
  },

  // ===== CONGENBILL (BIMCO Bill of Lading for GENCON voyages) — summary, full text paywalled =====
  {
    id: 'congenbill-summary',
    charterParty: 'CONGENBILL',
    clauseNumber: 'SUMMARY',
    title: 'CONGENBILL Bill of Lading Overview',
    text: 'CONGENBILL is the BIMCO standard bill of lading for use with GENCON voyage charter parties (current edition 2022). Incorporates GENCON terms by reference, provides title to goods and evidence of contract of carriage. Used worldwide in dry bulk trades. Three originals issued per shipment; consignee endorsement required for cargo release. Full B/L text paywalled via BIMCO membership — summary based on public BIMCO contract index.',
    sourceUrl: 'https://www.bimco.org/contracts-and-clauses/bimco-contracts/congenbill-2022',
  },
];
