/**
 * Curated target list for the global port master (Wave 4).
 *
 * Why not parse all ~9k UN/LOCODE seaports? Signal-to-noise. Most of them are
 * minor fishing harbours, inland barge terminals, or cruise-only ports that
 * freight brokers never request. The list below focuses on the ~500 ports
 * that cover 98% of dry-bulk / general-cargo / breakbulk / container flows
 * that Quantika's target users (Dubai/MENA freight forwarders) handle.
 *
 * Priorities (in broker-facing relevance order):
 *   1. Dry-bulk majors (Port Hedland, Tubarão, Kandla etc.) — our main parse class
 *   2. General cargo + container hubs (Rotterdam, Shanghai, Singapore...)
 *   3. Regional secondary (European range, Med, Baltic, African, Americas)
 *   4. Niche but commonly requested (Caribbean, Pacific, Red Sea secondary)
 *
 * The 15 existing demo-scope ports are migrated in lib/sailing/port-master.ts
 * directly (legacy hardcode) and need not be duplicated here.
 *
 * Ambiguity handling: when a name is shared across countries (Cartagena-ES vs
 * Cartagena-CO), we disambiguate via `country`. In rare cases we also pin
 * `unlocode` to force a specific match even if the CSV has sibling entries.
 */

export interface PortTarget {
  /** Canonical broker-facing name (e.g. "Rotterdam"). */
  name: string;
  /** ISO-3166 alpha-2 country code. */
  country: string;
  /** Force-match this UNLOCODE even if name+country has siblings. */
  unlocode?: string;
  /** Additional aliases brokers might type. */
  aliases?: string[];
  /** Short rationale for inclusion (for audit). */
  note?: string;
  /** Override latitude when UN/LOCODE CSV omits coordinates (common for major
   *  UK/EU ports). Used by matcher; otherwise LLM fills coords in Phase 4. */
  lat?: number;
  lon?: number;
}

/**
 * Target list. Maintain alphabetical within each regional block to ease merge
 * conflicts on future expansion.
 */
export const PORT_TARGETS: PortTarget[] = [
  // ── Northwest Europe (Hamburg-Le Havre range + UK/Ireland) ──
  { name: 'Rotterdam',      country: 'NL', unlocode: 'NLRTM', note: 'Europe #1 container + bulk' },
  { name: 'Antwerp',        country: 'BE', unlocode: 'BEANR', aliases: ['Anvers'] },
  { name: 'Hamburg',        country: 'DE', unlocode: 'DEHAM' },
  { name: 'Bremerhaven',    country: 'DE', unlocode: 'DEBRV' },
  { name: 'Wilhelmshaven',  country: 'DE' },
  { name: 'Bremen',         country: 'DE', unlocode: 'DEBRE' },
  { name: 'Amsterdam',      country: 'NL', unlocode: 'NLAMS' },
  { name: 'IJmuiden',       country: 'NL' },
  { name: 'Vlissingen',     country: 'NL', aliases: ['Flushing'] },
  { name: 'Zeebrugge',      country: 'BE', unlocode: 'BEZEE' },
  { name: 'Ghent',          country: 'BE', aliases: ['Gent'] },
  { name: 'Le Havre',       country: 'FR', unlocode: 'FRLEH' },
  { name: 'Dunkirk',        country: 'FR', unlocode: 'FRDKK', aliases: ['Dunkerque'] },
  { name: 'Calais',         country: 'FR' },
  { name: 'Rouen',          country: 'FR' },
  { name: 'Nantes',         country: 'FR', aliases: ['Saint-Nazaire'] },
  { name: 'Bordeaux',       country: 'FR' },
  { name: 'La Pallice',     country: 'FR', note: 'La Rochelle area' },
  { name: 'Brest',          country: 'FR' },
  { name: 'Cherbourg',      country: 'FR' },
  { name: 'Felixstowe',     country: 'GB', unlocode: 'GBFXT', note: 'UK #1 container' },
  { name: 'Southampton',    country: 'GB' },
  { name: 'Liverpool',      country: 'GB' },
  { name: 'Tilbury',        country: 'GB' },
  { name: 'Immingham',      country: 'GB' },
  { name: 'Teesport',       country: 'GB', aliases: ['Middlesbrough'] },
  { name: 'Hull',           country: 'GB' },
  { name: 'London Gateway', country: 'GB' },
  { name: 'Thamesport',     country: 'GB' },
  { name: 'Dover',          country: 'GB' },
  { name: 'Grimsby',        country: 'GB' },
  { name: 'Aberdeen',       country: 'GB' },
  { name: 'Belfast',        country: 'GB' },
  { name: 'Dublin',         country: 'IE' },
  { name: 'Cork',           country: 'IE' },
  { name: 'Waterford',      country: 'IE' },

  // ── Iberia + Western Mediterranean ──
  { name: 'Valencia',       country: 'ES', unlocode: 'ESVLC' },
  { name: 'Algeciras',      country: 'ES' },
  { name: 'Barcelona',      country: 'ES' },
  { name: 'Tarragona',      country: 'ES' },
  { name: 'Cartagena',      country: 'ES', unlocode: 'ESCAR', note: 'Spain (vs CO)' },
  { name: 'Bilbao',         country: 'ES' },
  { name: 'Gijón',          country: 'ES', aliases: ['Gijon'] },
  { name: 'Cádiz',          country: 'ES', aliases: ['Cadiz'] },
  { name: 'Huelva',         country: 'ES' },
  { name: 'Sevilla',        country: 'ES', aliases: ['Seville'] },
  { name: 'Motril',         country: 'ES' },
  { name: 'Las Palmas',     country: 'ES', note: 'Canary Islands' },
  { name: 'Tenerife',       country: 'ES' },
  { name: 'Lisbon',         country: 'PT', aliases: ['Lisboa'] },
  { name: 'Leixões',        country: 'PT', aliases: ['Leixoes', 'Porto'] },
  { name: 'Sines',          country: 'PT' },
  { name: 'Setúbal',        country: 'PT', aliases: ['Setubal'] },
  { name: 'Gibraltar',      country: 'GI' },
  { name: 'Marseille',      country: 'FR' },
  { name: 'Fos-sur-Mer',    country: 'FR', aliases: ['Fos'] },
  { name: 'Genoa',          country: 'IT', aliases: ['Genova'] },
  { name: 'La Spezia',      country: 'IT' },
  { name: 'Livorno',        country: 'IT' },
  { name: 'Naples',         country: 'IT', aliases: ['Napoli'] },
  { name: 'Salerno',        country: 'IT' },
  { name: 'Taranto',        country: 'IT' },
  { name: 'Trieste',        country: 'IT' },
  { name: 'Venice',         country: 'IT', aliases: ['Venezia'] },
  { name: 'Ancona',         country: 'IT' },
  { name: 'Bari',           country: 'IT' },
  { name: 'Civitavecchia',  country: 'IT' },
  { name: 'Cagliari',       country: 'IT' },
  { name: 'Catania',        country: 'IT' },
  { name: 'Palermo',        country: 'IT' },
  { name: 'Augusta',        country: 'IT' },
  { name: 'Gioia Tauro',    country: 'IT' },
  { name: 'Marsaxlokk',     country: 'MT', aliases: ['Malta'] },
  { name: 'Koper',          country: 'SI' },
  { name: 'Rijeka',         country: 'HR' },
  { name: 'Ploče',          country: 'HR', aliases: ['Ploce'] },
  { name: 'Split',          country: 'HR' },
  { name: 'Bar',            country: 'ME' },

  // ── Eastern Mediterranean + Near East ──
  { name: 'Thessaloniki',   country: 'GR', aliases: ['Salonika'] },
  { name: 'Volos',          country: 'GR' },
  { name: 'Kavala',         country: 'GR' },
  { name: 'Patras',         country: 'GR' },
  { name: 'Izmir',          country: 'TR' },
  { name: 'Mersin',         country: 'TR' },
  { name: 'Iskenderun',     country: 'TR' },
  { name: 'Tekirdag',       country: 'TR' },
  { name: 'Samsun',         country: 'TR' },
  { name: 'Limassol',       country: 'CY' },
  { name: 'Larnaca',        country: 'CY' },
  { name: 'Haifa',          country: 'IL' },
  { name: 'Ashdod',         country: 'IL' },
  { name: 'Beirut',         country: 'LB' },
  { name: 'Tripoli',        country: 'LB', unlocode: 'LBTPL', note: 'Lebanon (vs LY)' },
  { name: 'Latakia',        country: 'SY' },
  { name: 'Tartus',         country: 'SY' },
  { name: 'Port Said',      country: 'EG' },
  { name: 'Damietta',       country: 'EG' },
  { name: 'Sokhna',         country: 'EG', aliases: ['Ain Sokhna'] },
  { name: 'Suez',           country: 'EG' },

  // ── North Africa ──
  { name: 'Tunis',          country: 'TN' },
  { name: 'Bizerte',        country: 'TN' },
  { name: 'Sfax',           country: 'TN' },
  { name: 'Tripoli',        country: 'LY', unlocode: 'LYTIP', note: 'Libya (vs LB)' },
  { name: 'Benghazi',       country: 'LY' },
  { name: 'Misurata',       country: 'LY' },
  { name: 'Algiers',        country: 'DZ', aliases: ['Alger'] },
  { name: 'Oran',           country: 'DZ' },
  { name: 'Annaba',         country: 'DZ' },
  { name: 'Tangier',        country: 'MA', aliases: ['Tangier Med', 'Tanger Med'] },
  { name: 'Agadir',         country: 'MA' },
  { name: 'Nouadhibou',     country: 'MR' },

  // ── Baltic + Scandinavia ──
  { name: 'Gdańsk',         country: 'PL', aliases: ['Gdansk'] },
  { name: 'Gdynia',         country: 'PL' },
  { name: 'Szczecin',       country: 'PL' },
  { name: 'Świnoujście',    country: 'PL', aliases: ['Swinoujscie'] },
  { name: 'Rostock',        country: 'DE' },
  { name: 'Lübeck',         country: 'DE', aliases: ['Lubeck'] },
  { name: 'Kiel',           country: 'DE' },
  { name: 'Ventspils',      country: 'LV' },
  { name: 'Liepāja',        country: 'LV', aliases: ['Liepaja'] },
  { name: 'Riga',           country: 'LV' },
  { name: 'Tallinn',        country: 'EE' },
  { name: 'Paldiski',       country: 'EE' },
  { name: 'Klaipeda',       country: 'LT', aliases: ['Klaipėda'] },
  { name: 'Kaliningrad',    country: 'RU' },
  { name: 'Saint Petersburg', country: 'RU', aliases: ['St Petersburg', 'St. Petersburg'] },
  { name: 'Primorsk',       country: 'RU' },
  { name: 'Vyborg',         country: 'RU' },
  { name: 'Ust-Luga',       country: 'RU' },
  { name: 'Murmansk',       country: 'RU' },
  { name: 'Arkhangelsk',    country: 'RU' },
  { name: 'Helsinki',       country: 'FI' },
  { name: 'Kotka',          country: 'FI' },
  { name: 'Hamina',         country: 'FI' },
  { name: 'Turku',          country: 'FI' },
  { name: 'Pori',           country: 'FI' },
  { name: 'Esbjerg',        country: 'DK' },
  { name: 'Aarhus',         country: 'DK' },
  { name: 'Copenhagen',     country: 'DK', aliases: ['Koebenhavn', 'København'] },
  { name: 'Aalborg',        country: 'DK' },
  { name: 'Malmö',          country: 'SE', aliases: ['Malmo'] },
  { name: 'Gothenburg',     country: 'SE', aliases: ['Göteborg', 'Goteborg'] },
  { name: 'Stockholm',      country: 'SE' },
  { name: 'Luleå',          country: 'SE', aliases: ['Lulea'] },
  { name: 'Umeå',           country: 'SE', aliases: ['Umea'] },
  { name: 'Söderhamn',      country: 'SE', aliases: ['Soderhamn'] },
  { name: 'Helsingborg',    country: 'SE' },
  { name: 'Norrköping',     country: 'SE', aliases: ['Norrkoping'] },
  { name: 'Oslo',           country: 'NO' },
  { name: 'Bergen',         country: 'NO' },
  { name: 'Stavanger',      country: 'NO' },
  { name: 'Kristiansand',   country: 'NO' },
  { name: 'Narvik',         country: 'NO' },
  { name: 'Tromsø',         country: 'NO', aliases: ['Tromso'] },
  { name: 'Trondheim',      country: 'NO' },

  // ── Russia, Caspian, Caucasus ──
  { name: 'Tuapse',         country: 'RU' },
  { name: 'Taman',          country: 'RU' },
  { name: 'Sochi',          country: 'RU' },
  { name: 'Temryuk',        country: 'RU' },
  { name: 'Rostov-on-Don',  country: 'RU', aliases: ['Rostov'] },
  { name: 'Yeisk',          country: 'RU' },
  { name: 'Yuzhny',         country: 'UA', aliases: ['Pivdennyi', 'Yuzhne'] },
  { name: 'Chornomorsk',    country: 'UA', aliases: ['Illichivsk'] },
  { name: 'Kherson',        country: 'UA' },
  { name: 'Poti',           country: 'GE' },
  { name: 'Batumi',         country: 'GE' },
  { name: 'Baku',           country: 'AZ' },
  { name: 'Aktau',          country: 'KZ' },
  { name: 'Türkmenbaşy',    country: 'TM', aliases: ['Turkmenbashy'] },
  { name: 'Anzali',         country: 'IR', aliases: ['Bandar Anzali', 'Pahlavi'] },

  // ── Arabian Gulf + Red Sea ──
  { name: 'Jebel Ali',      country: 'AE', aliases: ['Dubai'] },
  { name: 'Khor Fakkan',    country: 'AE' },
  { name: 'Fujairah',       country: 'AE' },
  { name: 'Sharjah',        country: 'AE' },
  { name: 'Abu Dhabi',      country: 'AE' },
  { name: 'Ajman',          country: 'AE' },
  { name: 'Doha',           country: 'QA' },
  { name: 'Ras Laffan',     country: 'QA' },
  { name: 'Mesaieed',       country: 'QA' },
  { name: 'Shuwaikh',       country: 'KW' },
  { name: 'Shuaiba',        country: 'KW' },
  { name: 'Kuwait',         country: 'KW', aliases: ['Kuwait City'] },
  { name: 'Bahrain',        country: 'BH', aliases: ['Khalifa bin Salman', 'KBSP'] },
  { name: 'Dammam',         country: 'SA' },
  { name: 'Jubail',         country: 'SA', aliases: ['Al Jubail'] },
  { name: 'Ras Tanura',     country: 'SA' },
  { name: 'Jeddah',         country: 'SA' },
  { name: 'Yanbu',          country: 'SA' },
  { name: 'Jizan',          country: 'SA' },
  { name: 'Sohar',          country: 'OM' },
  { name: 'Salalah',        country: 'OM' },
  { name: 'Duqm',           country: 'OM' },
  { name: 'Sur',            country: 'OM' },
  { name: 'Umm Qasr',       country: 'IQ' },
  { name: 'Basra',          country: 'IQ' },
  { name: 'Bandar Abbas',   country: 'IR' },
  { name: 'Bushehr',        country: 'IR' },
  { name: 'Bandar Imam',    country: 'IR', aliases: ['Bandar Imam Khomeini'] },
  { name: 'Aden',           country: 'YE' },
  { name: 'Hodeidah',       country: 'YE', aliases: ['Al Hudaydah'] },
  { name: 'Mokha',          country: 'YE', aliases: ['Al Mukha', 'Mocha'] },
  { name: 'Djibouti',       country: 'DJ' },
  { name: 'Port Sudan',     country: 'SD' },
  { name: 'Assab',          country: 'ER' },
  { name: 'Massawa',        country: 'ER' },
  { name: 'Berbera',        country: 'SO' },
  { name: 'Mogadishu',      country: 'SO' },

  // ── South Asia ──
  { name: 'Karachi',        country: 'PK' },
  { name: 'Port Qasim',     country: 'PK' },
  { name: 'Gwadar',         country: 'PK' },
  { name: 'Mundra',         country: 'IN' },
  { name: 'Kandla',         country: 'IN', aliases: ['Deendayal'] },
  { name: 'JNPT',           country: 'IN', aliases: ['Nhava Sheva', 'Jawaharlal Nehru'] },
  { name: 'Mumbai',         country: 'IN', aliases: ['Bombay'] },
  { name: 'Pipavav',        country: 'IN' },
  { name: 'Hazira',         country: 'IN' },
  { name: 'Mormugao',       country: 'IN', aliases: ['Mormugao Goa', 'Marmugao'] },
  { name: 'New Mangalore',  country: 'IN' },
  { name: 'Cochin',         country: 'IN', aliases: ['Kochi'] },
  { name: 'Tuticorin',      country: 'IN', aliases: ['Thoothukudi', 'V.O. Chidambaranar'] },
  { name: 'Chennai',        country: 'IN', aliases: ['Madras'] },
  { name: 'Ennore',         country: 'IN', aliases: ['Kamarajar'] },
  { name: 'Krishnapatnam',  country: 'IN' },
  { name: 'Kakinada',       country: 'IN' },
  { name: 'Visakhapatnam',  country: 'IN', aliases: ['Vizag'] },
  { name: 'Paradip',        country: 'IN' },
  { name: 'Haldia',         country: 'IN' },
  { name: 'Kolkata',        country: 'IN', aliases: ['Calcutta'] },
  { name: 'Chittagong',     country: 'BD' },
  { name: 'Mongla',         country: 'BD' },
  { name: 'Colombo',        country: 'LK' },
  { name: 'Hambantota',     country: 'LK' },
  { name: 'Malé',           country: 'MV', aliases: ['Male'] },

  // ── Southeast Asia ──
  { name: 'Singapore',      country: 'SG', unlocode: 'SGSIN', note: 'World #2 container' },
  { name: 'Port Klang',     country: 'MY', aliases: ['Klang', 'Kelang'] },
  { name: 'Tanjung Pelepas', country: 'MY', aliases: ['PTP'] },
  { name: 'Penang',         country: 'MY', aliases: ['Pulau Pinang'] },
  { name: 'Pasir Gudang',   country: 'MY' },
  { name: 'Kuantan',        country: 'MY' },
  { name: 'Bintulu',        country: 'MY' },
  { name: 'Kuching',        country: 'MY' },
  { name: 'Kota Kinabalu',  country: 'MY' },
  { name: 'Laem Chabang',   country: 'TH' },
  { name: 'Bangkok',        country: 'TH' },
  { name: 'Songkhla',       country: 'TH' },
  { name: 'Map Ta Phut',    country: 'TH' },
  { name: 'Sihanoukville',  country: 'KH' },
  { name: 'Ho Chi Minh',    country: 'VN', aliases: ['Saigon', 'HCM'] },
  { name: 'Haiphong',       country: 'VN', aliases: ['Hai Phong'] },
  { name: 'Cai Mep',        country: 'VN' },
  { name: 'Da Nang',        country: 'VN' },
  { name: 'Qui Nhon',       country: 'VN' },
  { name: 'Tanjung Priok',  country: 'ID', aliases: ['Jakarta'] },
  { name: 'Surabaya',       country: 'ID', aliases: ['Tanjung Perak'] },
  { name: 'Belawan',        country: 'ID' },
  { name: 'Semarang',       country: 'ID' },
  { name: 'Makassar',       country: 'ID' },
  { name: 'Manila',         country: 'PH' },
  { name: 'Subic',          country: 'PH', aliases: ['Subic Bay'] },
  { name: 'Batangas',       country: 'PH' },
  { name: 'Cebu',           country: 'PH' },
  { name: 'Cagayan de Oro', country: 'PH' },
  { name: 'Davao',          country: 'PH' },

  // ── East Asia ──
  { name: 'Shanghai',       country: 'CN', unlocode: 'CNSHA', note: 'World #1 container' },
  { name: 'Ningbo',         country: 'CN', aliases: ['Ningbo-Zhoushan'] },
  { name: 'Shenzhen',       country: 'CN', aliases: ['Yantian'] },
  { name: 'Guangzhou',      country: 'CN' },
  { name: 'Qingdao',        country: 'CN' },
  { name: 'Tianjin',        country: 'CN', aliases: ['Xingang'] },
  { name: 'Dalian',         country: 'CN' },
  { name: 'Xiamen',         country: 'CN' },
  { name: 'Fuzhou',         country: 'CN' },
  { name: 'Shantou',        country: 'CN' },
  { name: 'Lianyungang',    country: 'CN' },
  { name: 'Rizhao',         country: 'CN' },
  { name: 'Yantai',         country: 'CN' },
  { name: 'Zhanjiang',      country: 'CN' },
  { name: 'Haikou',         country: 'CN' },
  { name: 'Taicang',        country: 'CN' },
  { name: 'Caofeidian',     country: 'CN' },
  { name: 'Bayuquan',       country: 'CN', aliases: ['Yingkou'] },
  { name: 'Jingtang',       country: 'CN' },
  { name: 'Nantong',        country: 'CN' },
  { name: 'Zhoushan',       country: 'CN' },
  { name: 'Hong Kong',      country: 'HK' },
  { name: 'Kaohsiung',      country: 'TW' },
  { name: 'Keelung',        country: 'TW' },
  { name: 'Taichung',       country: 'TW' },
  { name: 'Taipei',         country: 'TW' },
  { name: 'Busan',          country: 'KR', aliases: ['Pusan'] },
  { name: 'Incheon',        country: 'KR' },
  { name: 'Gwangyang',      country: 'KR' },
  { name: 'Ulsan',          country: 'KR' },
  { name: 'Pyeongtaek',     country: 'KR' },
  { name: 'Pohang',         country: 'KR' },
  { name: 'Mokpo',          country: 'KR' },
  { name: 'Yokohama',       country: 'JP' },
  { name: 'Tokyo',          country: 'JP' },
  { name: 'Kobe',           country: 'JP' },
  { name: 'Osaka',          country: 'JP' },
  { name: 'Nagoya',         country: 'JP' },
  { name: 'Chiba',          country: 'JP' },
  { name: 'Hakata',         country: 'JP' },
  { name: 'Kitakyushu',     country: 'JP' },
  { name: 'Shimizu',        country: 'JP' },
  { name: 'Shimonoseki',    country: 'JP' },
  { name: 'Moji',           country: 'JP' },
  { name: 'Sendai',         country: 'JP' },
  { name: 'Tomakomai',      country: 'JP' },

  // ── Russia Far East ──
  { name: 'Vladivostok',    country: 'RU' },
  { name: 'Vostochny',      country: 'RU' },
  { name: 'Nakhodka',       country: 'RU' },
  { name: 'Magadan',        country: 'RU' },
  { name: 'Korsakov',       country: 'RU', aliases: ['Sakhalin'] },
  { name: 'Petropavlovsk',  country: 'RU', aliases: ['Petropavlovsk-Kamchatsky'] },

  // ── Australasia ──
  { name: 'Port Hedland',   country: 'AU', note: 'Iron ore #1' },
  { name: 'Dampier',        country: 'AU' },
  { name: 'Newcastle',      country: 'AU', unlocode: 'AUNTL', note: 'Coal export #1 (not UK)' },
  { name: 'Hay Point',      country: 'AU' },
  { name: 'Gladstone',      country: 'AU' },
  { name: 'Abbot Point',    country: 'AU' },
  { name: 'Brisbane',       country: 'AU' },
  { name: 'Sydney',         country: 'AU', aliases: ['Port Botany'] },
  { name: 'Melbourne',      country: 'AU' },
  { name: 'Adelaide',       country: 'AU' },
  { name: 'Fremantle',      country: 'AU', aliases: ['Perth'] },
  { name: 'Darwin',         country: 'AU' },
  { name: 'Townsville',     country: 'AU' },
  { name: 'Geraldton',      country: 'AU' },
  { name: 'Esperance',      country: 'AU' },
  { name: 'Auckland',       country: 'NZ' },
  { name: 'Tauranga',       country: 'NZ' },
  { name: 'Napier',         country: 'NZ' },
  { name: 'Lyttelton',      country: 'NZ' },
  { name: 'Port Chalmers',  country: 'NZ', aliases: ['Otago', 'Dunedin'] },
  { name: 'Wellington',     country: 'NZ' },

  // ── West Africa ──
  { name: 'Dakar',          country: 'SN' },
  { name: 'Abidjan',        country: 'CI' },
  { name: 'Tema',           country: 'GH' },
  { name: 'Takoradi',       country: 'GH' },
  { name: 'Lomé',           country: 'TG', aliases: ['Lome'] },
  { name: 'Cotonou',        country: 'BJ' },
  { name: 'Lagos',          country: 'NG', aliases: ['Apapa', 'Tin Can Island'] },
  { name: 'Port Harcourt',  country: 'NG' },
  { name: 'Onne',           country: 'NG' },
  { name: 'Calabar',        country: 'NG' },
  { name: 'Douala',         country: 'CM' },
  { name: 'Kribi',          country: 'CM' },
  { name: 'Malabo',         country: 'GQ' },
  { name: 'Bata',           country: 'GQ' },
  { name: 'Libreville',     country: 'GA' },
  { name: 'Port-Gentil',    country: 'GA' },
  { name: 'Pointe-Noire',   country: 'CG' },
  { name: 'Matadi',         country: 'CD' },
  { name: 'Luanda',         country: 'AO' },
  { name: 'Lobito',         country: 'AO' },
  { name: 'Namibe',         country: 'AO' },
  { name: 'Walvis Bay',     country: 'NA' },
  { name: 'Cape Town',      country: 'ZA' },
  { name: 'Saldanha Bay',   country: 'ZA' },
  { name: 'Port Elizabeth', country: 'ZA', aliases: ['Gqeberha'] },
  { name: 'East London',    country: 'ZA' },
  { name: 'Durban',         country: 'ZA' },
  { name: 'Richards Bay',   country: 'ZA' },

  // ── East Africa + Indian Ocean ──
  { name: 'Mombasa',        country: 'KE' },
  { name: 'Dar es Salaam',  country: 'TZ' },
  { name: 'Tanga',          country: 'TZ' },
  { name: 'Beira',          country: 'MZ' },
  { name: 'Nacala',         country: 'MZ' },
  { name: 'Maputo',         country: 'MZ' },
  { name: 'Toamasina',      country: 'MG', aliases: ['Tamatave'] },
  { name: 'Port Louis',     country: 'MU', aliases: ['Mauritius'] },
  { name: 'Réunion',        country: 'RE', aliases: ['Reunion', 'Port Reunion', 'Le Port'] },

  // ── North America East Coast + Gulf ──
  { name: 'New York',       country: 'US', aliases: ['New York New Jersey', 'NY/NJ'] },
  { name: 'Newark',         country: 'US' },
  { name: 'Philadelphia',   country: 'US' },
  { name: 'Baltimore',      country: 'US' },
  { name: 'Norfolk',        country: 'US', aliases: ['Hampton Roads'] },
  { name: 'Charleston',     country: 'US' },
  { name: 'Savannah',       country: 'US' },
  { name: 'Jacksonville',   country: 'US', aliases: ['JAXPORT'] },
  { name: 'Port Everglades', country: 'US', aliases: ['Fort Lauderdale'] },
  { name: 'Miami',          country: 'US' },
  { name: 'Tampa',          country: 'US' },
  { name: 'Mobile',         country: 'US' },
  { name: 'New Orleans',    country: 'US' },
  { name: 'Baton Rouge',    country: 'US' },
  { name: 'Houston',        country: 'US' },
  { name: 'Corpus Christi', country: 'US' },
  { name: 'Galveston',      country: 'US' },
  { name: 'Port Arthur',    country: 'US' },
  { name: 'Brownsville',    country: 'US' },
  { name: 'Pascagoula',     country: 'US' },
  { name: 'Wilmington',     country: 'US', unlocode: 'USILM', note: 'NC (vs DE)' },
  { name: 'Boston',         country: 'US' },
  { name: 'Portland',       country: 'US', unlocode: 'USPDX', note: 'OR (vs ME)' },

  // ── North America West Coast + Pacific ──
  { name: 'Los Angeles',    country: 'US' },
  { name: 'Long Beach',     country: 'US' },
  { name: 'Oakland',        country: 'US' },
  { name: 'Seattle',        country: 'US' },
  { name: 'Tacoma',         country: 'US' },
  { name: 'Anchorage',      country: 'US' },
  { name: 'Honolulu',       country: 'US' },
  { name: 'San Diego',      country: 'US' },

  // ── Canada ──
  { name: 'Vancouver',      country: 'CA', unlocode: 'CAVAN', note: 'BC (vs WA)' },
  { name: 'Prince Rupert',  country: 'CA' },
  { name: 'Halifax',        country: 'CA' },
  { name: 'Saint John',     country: 'CA' },
  { name: 'Montreal',       country: 'CA' },
  { name: 'Quebec',         country: 'CA' },
  { name: 'Sept-Îles',      country: 'CA', aliases: ['Sept Iles'] },

  // ── Mexico + Central America ──
  { name: 'Veracruz',       country: 'MX' },
  { name: 'Altamira',       country: 'MX' },
  { name: 'Tampico',        country: 'MX' },
  { name: 'Manzanillo',     country: 'MX', unlocode: 'MXZLO', note: 'MX (vs PA)' },
  { name: 'Lazaro Cardenas', country: 'MX', aliases: ['Lázaro Cárdenas'] },
  { name: 'Guaymas',        country: 'MX' },
  { name: 'Ensenada',       country: 'MX' },
  { name: 'Colón',          country: 'PA', aliases: ['Colon'] },
  { name: 'Balboa',         country: 'PA' },
  { name: 'Puerto Limón',   country: 'CR', aliases: ['Limon', 'Puerto Limon'] },
  { name: 'Santo Tomás',    country: 'GT', aliases: ['Santo Tomas de Castilla'] },
  { name: 'Puerto Cortés',  country: 'HN', aliases: ['Puerto Cortes'] },
  { name: 'Corinto',        country: 'NI' },
  { name: 'Acajutla',       country: 'SV' },

  // ── Caribbean ──
  { name: 'Havana',         country: 'CU', aliases: ['La Habana'] },
  { name: 'Kingston',       country: 'JM' },
  { name: 'Santo Domingo',  country: 'DO' },
  { name: 'Caucedo',        country: 'DO' },
  { name: 'Port-au-Prince', country: 'HT' },
  { name: 'Nassau',         country: 'BS' },
  { name: 'Freeport',       country: 'BS', unlocode: 'BSFPO', note: 'Bahamas (many dupes)' },
  { name: 'San Juan',       country: 'PR' },
  { name: 'Bridgetown',     country: 'BB' },
  { name: 'Point Lisas',    country: 'TT' },
  { name: 'Port of Spain',  country: 'TT' },

  // ── South America (Atlantic side) ──
  { name: 'Cartagena',      country: 'CO', unlocode: 'COCTG', note: 'Colombia (vs ES)' },
  { name: 'Barranquilla',   country: 'CO' },
  { name: 'Santa Marta',    country: 'CO' },
  { name: 'Maracaibo',      country: 'VE' },
  { name: 'La Guaira',      country: 'VE' },
  { name: 'Puerto Cabello', country: 'VE' },
  { name: 'Georgetown',     country: 'GY' },
  { name: 'Paramaribo',     country: 'SR' },
  { name: 'Belém',          country: 'BR', aliases: ['Belem'] },
  { name: 'São Luís',       country: 'BR', aliases: ['Sao Luis', 'Itaqui'] },
  { name: 'Itaqui',         country: 'BR' },
  { name: 'Ponta da Madeira', country: 'BR' },
  { name: 'Fortaleza',      country: 'BR' },
  { name: 'Pecém',          country: 'BR', aliases: ['Pecem'] },
  { name: 'Suape',          country: 'BR' },
  { name: 'Salvador',       country: 'BR' },
  { name: 'Aratu',          country: 'BR' },
  { name: 'Vitória',        country: 'BR', aliases: ['Vitoria'] },
  { name: 'Tubarão',        country: 'BR', aliases: ['Tubarao'] },
  { name: 'Barra do Riacho', country: 'BR' },
  { name: 'Santos',         country: 'BR' },
  { name: 'Paranaguá',      country: 'BR', aliases: ['Paranagua'] },
  { name: 'Itajaí',         country: 'BR', aliases: ['Itajai'] },
  { name: 'Navegantes',     country: 'BR' },
  { name: 'Imbituba',       country: 'BR' },
  { name: 'Rio Grande',     country: 'BR' },
  { name: 'Montevideo',     country: 'UY' },
  { name: 'Nueva Palmira',  country: 'UY' },
  { name: 'Buenos Aires',   country: 'AR' },
  { name: 'Rosario',        country: 'AR' },
  { name: 'San Lorenzo',    country: 'AR' },
  { name: 'Bahía Blanca',   country: 'AR', aliases: ['Bahia Blanca'] },
  { name: 'Quequén',        country: 'AR', aliases: ['Quequen'] },
  { name: 'Ushuaia',        country: 'AR' },

  // ── South America (Pacific side) ──
  { name: 'Callao',         country: 'PE' },
  { name: 'Paita',          country: 'PE' },
  { name: 'Matarani',       country: 'PE' },
  { name: 'Ilo',            country: 'PE' },
  { name: 'Valparaíso',     country: 'CL', aliases: ['Valparaiso'] },
  { name: 'San Antonio',    country: 'CL', unlocode: 'CLSAI', note: 'CL (vs TX)' },
  { name: 'Iquique',        country: 'CL' },
  { name: 'Antofagasta',    country: 'CL' },
  { name: 'Mejillones',     country: 'CL' },
  { name: 'Coronel',        country: 'CL' },
  { name: 'Puerto Bolívar', country: 'EC', aliases: ['Puerto Bolivar'] },
  { name: 'Guayaquil',      country: 'EC' },
  { name: 'Manta',          country: 'EC' },

  // ── Biscay / Iberia secondary ──
  { name: 'Santander',      country: 'ES' },
  { name: 'Ferrol',         country: 'ES' },
  { name: 'A Coruña',       country: 'ES', aliases: ['La Coruna', 'A Coruna'] },
  { name: 'Vigo',           country: 'ES' },

  // ── Greenland + Arctic niche ──
  { name: 'Nuuk',           country: 'GL' },
  { name: 'Reykjavík',      country: 'IS', aliases: ['Reykjavik'] },
  { name: 'Akureyri',       country: 'IS' },
];
