/**
 * Structural-invariants test for the sample-data email fixtures.
 *
 * Before the ETMS-corpus migration (2026-05-14) this test pinned exact
 * counts and the sample-NN ID pattern. After migration the corpus is
 * regenerated by scripts/build-sample-data.ts from real emails, so the
 * test instead asserts invariants that any valid generator output must
 * satisfy.
 */

import cargoInquiries from '@/lib/sample-data/cargo-inquiries.json';
import vesselPositions from '@/lib/sample-data/vessel-positions.json';
import fixtureRecaps from '@/lib/sample-data/fixture-recaps.json';
import clientReplies from '@/lib/sample-data/client-replies.json';
import documents from '@/lib/sample-data/documents.json';
import vesselCerts from '@/lib/sample-data/vessel-certs.json';

const SAMPLE_EMAILS = [
  ...cargoInquiries,
  ...vesselPositions,
  ...fixtureRecaps,
  ...clientReplies,
  ...documents,
  ...vesselCerts,
];

describe('SAMPLE_EMAILS structural invariants', () => {
  it('is non-empty', () => {
    expect(SAMPLE_EMAILS.length).toBeGreaterThan(0);
  });

  it('every email has the required Email fields', () => {
    for (const email of SAMPLE_EMAILS) {
      expect(typeof email.id).toBe('string');
      expect(email.id.length).toBeGreaterThan(0);
      expect(typeof email.subject).toBe('string');
      expect(typeof email.from).toBe('string');
      expect(typeof email.body).toBe('string');
      expect(email.body.length).toBeGreaterThan(0);
      expect(typeof email.date).toBe('string');
    }
  });

  it('every email carries _meta with a numeric emailDateOffsetDays', () => {
    for (const email of SAMPLE_EMAILS) {
      expect(email).toHaveProperty('_meta');
      expect(typeof email._meta.emailDateOffsetDays).toBe('number');
      // Offsets are 0 (newest) or negative (older). Positive would mean a
      // future-dated email relative to the newest, which is impossible.
      expect(email._meta.emailDateOffsetDays).toBeLessThanOrEqual(0);
    }
  });

  it('all ids are unique across the whole corpus', () => {
    const ids = SAMPLE_EMAILS.map((e) => e.id);
    const unique = new Set(ids);
    expect(unique.size).toBe(ids.length);
  });

  it('at least one email has offset 0 (the newest)', () => {
    const newest = SAMPLE_EMAILS.filter((e) => e._meta.emailDateOffsetDays === 0);
    expect(newest.length).toBeGreaterThanOrEqual(1);
  });
});
